name: CI/CD Pipeline
# Pipeline by Adil CHETOUANI

on:
    push:
        branches:
            - main
            - develop
            - release/*
            - feature/*
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 20

            - name: Install Dependencies
              run: |
                  npm install --legacy-peer-deps

            - name: Build
              run: |
                  npm run build

    package:
        needs: build
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: write

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 20

            - name: Set Git Bot
              run: |
                  git config user.name "Adil Bot"
                  git config user.email "onizuka9361@gmail.com"

            - name: Update local branch
              run: |
                  BRANCH_NAME=${GITHUB_REF#refs/heads/}
                  git pull origin ${BRANCH_NAME} --rebase

            - name: Version handling
              run: |
                  BRANCH_NAME=${GITHUB_REF#refs/heads/}
                  VERSION=$(node -p "require('./package.json').version")

                  if [[ "$BRANCH_NAME" == "develop" ]]; then
                    npm version patch
                  elif [[ "$BRANCH_NAME" =~ ^feature/ ]]; then
                    npm version prerelease --preid=snapshot
                  fi

                  git push origin $BRANCH_NAME --tags
